services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - frontend-network
      - backend-network
    ports:
      - "8000:8000"
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - backend-network
    ports:
      - "8080:80"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  frontend-network:
  backend-network:

volumes:
  db_data:
